services:
  # Base de Datos Relacional PostgreSQL 15
  db:
    image: postgres:15-alpine
    container_name: rh_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin_rh}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-TuPasswordSeguro123!}
      POSTGRES_DB: ${POSTGRES_DB:-db_recursos_humanos}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin_rh} -d ${POSTGRES_DB:-db_recursos_humanos}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rh_network

  # Caché de Sesiones y Mensajería en Tiempo Real con Redis
  redis:
    image: redis:7-alpine
    container_name: rh_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - rh_network

  # Servidor Backend API Express + Prisma + WebSockets + Almacenamiento Local Persistente
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${BACKEND_IMAGE:-rh-backend:latest}
    container_name: rh_backend
    restart: always
    environment:
      PORT: 5000
      DATABASE_URL: ${DATABASE_URL:-postgresql://admin_rh:TuPasswordSeguro123!@db:5432/db_recursos_humanos?schema=public}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      JWT_SECRET: ${JWT_SECRET:-TuClaveSecretaUltraSegura}
      CLIENT_URL: ${CLIENT_URL:-https://erp.jorgedoicela.com}
      FRONTEND_URL: ${FRONTEND_URL:-https://erp.jorgedoicela.com}
      ORIGIN: ${ORIGIN:-https://erp.jorgedoicela.com}
      RP_ID: ${RP_ID:-erp.jorgedoicela.com}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-a4f89d71b3e92185c701fa591283e4bc0d9841f23789a2b4e56cd89101234567}
      SEED_SECRET: ${SEED_SECRET:-e9b817c2f043a19d8542b6e10a749321c568f9a20391d4e78b12f3456789abcd}
      EMAIL_USER: ${EMAIL_USER:-jorge.doicela.m@gmail.com}
      EMAIL_PASS: ${EMAIL_PASS:-huzakyvemzrtsewv}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rh_network

  # Servidor Frontend React SPA + Reverse Proxy Nginx SSL 443
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${FRONTEND_IMAGE:-rh-frontend:latest}
    container_name: rh_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/recursos_humanos/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    networks:
      - rh_network

volumes:
  postgres_data:
  redis_data:
  uploads_data:

networks:
  rh_network:
    driver: bridge
