import bcrypt from 'bcryptjs';
import { encrypt, encryptSalary } from '../../src/utils/encryption.js';

// 10 empleados reales ecuatorianos + 1 admin
// Contraseña de todos: Emplifi2025!
// Correos: nombre.apellido@emplifi.com

const EMPLOYEES = [
    {
        firstName: 'Andrés',
        lastName: 'Morales',
        email: 'andres.morales@emplifi.com',
        identityCard: '1712345678',
        department: 'Tecnología',
        position: 'Desarrollador Senior',
        salary: 2200,
        phone: '0991234567',
        address: 'Av. República del Salvador N36-84, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1990-03-15'),
        hireDate: new Date('2021-06-01'),
        bankName: 'Banco Pichincha',
        accountNumber: '2201234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Valeria',
        lastName: 'Espinoza',
        email: 'valeria.espinoza@emplifi.com',
        identityCard: '1723456789',
        department: 'Recursos Humanos',
        position: 'Coordinadora de RRHH',
        salary: 1800,
        phone: '0982345678',
        address: 'Calle Veintimilla E7-45, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1993-07-22'),
        hireDate: new Date('2020-03-15'),
        bankName: 'Banco Guayaquil',
        accountNumber: '3301234567',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Diego',
        lastName: 'Vásquez',
        email: 'diego.vasquez@emplifi.com',
        identityCard: '1734567890',
        department: 'Finanzas',
        position: 'Analista Financiero',
        salary: 1950,
        phone: '0973456789',
        address: 'Av. Naciones Unidas E10-44, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1988-11-08'),
        hireDate: new Date('2019-09-01'),
        bankName: 'Produbanco',
        accountNumber: '4401234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Gabriela',
        lastName: 'Torres',
        email: 'gabriela.torres@emplifi.com',
        identityCard: '1745678901',
        department: 'Marketing',
        position: 'Especialista en Marketing Digital',
        salary: 1700,
        phone: '0964567890',
        address: 'Calle Portugal E9-25, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1995-04-30'),
        hireDate: new Date('2022-01-10'),
        bankName: 'Banco Internacional',
        accountNumber: '5501234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Sebastián',
        lastName: 'Herrera',
        email: 'sebastian.herrera@emplifi.com',
        identityCard: '1756789012',
        department: 'Tecnología',
        position: 'Ingeniero DevOps',
        salary: 2500,
        phone: '0955678901',
        address: 'Av. Amazonas N21-147, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1991-09-14'),
        hireDate: new Date('2021-11-01'),
        bankName: 'Banco Pichincha',
        accountNumber: '6601234567',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Camila',
        lastName: 'Rodríguez',
        email: 'camila.rodriguez@emplifi.com',
        identityCard: '1767890123',
        department: 'Ventas',
        position: 'Ejecutiva de Ventas',
        salary: 1600,
        phone: '0946789012',
        address: 'Calle Shyris N36-188, Quito',
        civilStatus: 'Casada',
        contractType: 'Indefinido',
        birthDate: new Date('1994-01-25'),
        hireDate: new Date('2022-05-16'),
        bankName: 'Banco del Pacífico',
        accountNumber: '7701234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Mateo',
        lastName: 'Jiménez',
        email: 'mateo.jimenez@emplifi.com',
        identityCard: '1778901234',
        department: 'Operaciones',
        position: 'Coordinador de Operaciones',
        salary: 1850,
        phone: '0937890123',
        address: 'Av. 6 de Diciembre N24-358, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1987-06-03'),
        hireDate: new Date('2018-08-01'),
        bankName: 'Banco Guayaquil',
        accountNumber: '8801234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Daniela',
        lastName: 'Salazar',
        email: 'daniela.salazar@emplifi.com',
        identityCard: '1789012345',
        department: 'Legal',
        position: 'Asesora Legal',
        salary: 2100,
        phone: '0928901234',
        address: 'Calle Baquedano E5-29, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1992-12-17'),
        hireDate: new Date('2020-07-01'),
        bankName: 'Produbanco',
        accountNumber: '9901234567',
        accountType: 'Corriente',
        vacationDays: 15,
    },
    {
        firstName: 'Felipe',
        lastName: 'Castillo',
        email: 'felipe.castillo@emplifi.com',
        identityCard: '1790123456',
        department: 'Tecnología',
        position: 'Diseñador UX/UI',
        salary: 1900,
        phone: '0919012345',
        address: 'Av. Colón E4-60, Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1996-08-09'),
        hireDate: new Date('2023-02-01'),
        bankName: 'Banco Internacional',
        accountNumber: '1001234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Paola',
        lastName: 'Mendoza',
        email: 'paola.mendoza@emplifi.com',
        identityCard: '1701234567',
        department: 'Finanzas',
        position: 'Contadora General',
        salary: 2000,
        phone: '0901234567',
        address: 'Calle Roca E4-25, Quito',
        civilStatus: 'Casada',
        contractType: 'Indefinido',
        birthDate: new Date('1989-02-28'),
        hireDate: new Date('2019-04-15'),
        bankName: 'Banco Pichincha',
        accountNumber: '1101234567',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Kevin',
        lastName: 'Arismendi',
        email: 'kevin.arismendi@emplifi.com',
        identityCard: '1799988877',
        department: 'Tecnología',
        position: 'Junior Developer',
        salary: 950,
        phone: '0999888777',
        address: 'Av. El Inca, Quito',
        civilStatus: 'Soltero',
        contractType: 'Temporal',
        birthDate: new Date('2000-05-10'),
        hireDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000), // 2 meses de antigüedad (Riesgo)
        bankName: 'Produbanco',
        accountNumber: '1212121212',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Lucía',
        lastName: 'Pazmiño',
        email: 'lucia.paz@emplifi.com',
        identityCard: '1788877766',
        department: 'Marketing',
        position: 'Asistente Creativo',
        salary: 850,
        phone: '0988877766',
        address: 'Valle de los Chillos, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1992-10-12'),
        hireDate: new Date('2018-01-01'), // > 5 años (Sin promoción = Riesgo)
        bankName: 'Banco Pichincha',
        accountNumber: '3434343434',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    {
        firstName: 'Roberto',
        lastName: 'Guzmán',
        email: 'roberto.guzman@emplifi.com',
        identityCard: '1777766655',
        department: 'Ventas',
        position: 'Gerente de Ventas',
        salary: 3200,
        phone: '0977766655',
        address: 'Av. González Suárez, Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1984-11-20'),
        hireDate: new Date('2021-03-01'),
        bankName: 'Banco Guayaquil',
        accountNumber: '5566778899',
        accountType: 'Corriente',
        vacationDays: 20,
    },
    {
        firstName: 'Isabel',
        lastName: 'Fuentes',
        email: 'isabel.fuentes@emplifi.com',
        identityCard: '1766655544',
        department: 'Recursos Humanos',
        position: 'Analista de Capacitación y Desarrollo',
        salary: 1750,
        phone: '0966655544',
        address: 'Av. Eloy Alfaro, Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1994-05-14'),
        hireDate: new Date('2022-09-15'),
        bankName: 'Produbanco',
        accountNumber: '6677889900',
        accountType: 'Ahorros',
        vacationDays: 15,
    },
    // Ex-empleados desvinculados para generar tendencia de rotación histórica real en los últimos 6 meses
    {
        firstName: 'Carlos',
        lastName: 'Pérez',
        email: 'carlos.perez.ex@emplifi.com',
        identityCard: '1755544433',
        department: 'Ventas',
        position: 'Ejecutivo de Ventas',
        salary: 1400,
        phone: '0955544433',
        address: 'Quito',
        civilStatus: 'Soltero',
        contractType: 'Temporal',
        birthDate: new Date('1993-01-10'),
        hireDate: new Date('2023-01-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 5, 10), // Hace 5 meses (1 salida)
        isActive: false,
        bankName: 'Banco Pichincha',
        accountNumber: '1111222233',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Mariana',
        lastName: 'Silva',
        email: 'mariana.silva.ex@emplifi.com',
        identityCard: '1744433322',
        department: 'Marketing',
        position: 'Diseñadora Gráfica',
        salary: 1300,
        phone: '0944433322',
        address: 'Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1995-06-12'),
        hireDate: new Date('2022-04-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 4, 15), // Hace 4 meses (1 salida)
        isActive: false,
        bankName: 'Produbanco',
        accountNumber: '2222333344',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Jorge',
        lastName: 'Navarro',
        email: 'jorge.navarro.ex@emplifi.com',
        identityCard: '1733322211',
        department: 'Tecnología',
        position: 'Soporte Técnico',
        salary: 1100,
        phone: '0933322211',
        address: 'Quito',
        civilStatus: 'Soltero',
        contractType: 'Temporal',
        birthDate: new Date('1997-09-05'),
        hireDate: new Date('2023-05-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 3, 20), // Hace 3 meses (2 salidas)
        isActive: false,
        bankName: 'Banco Guayaquil',
        accountNumber: '3333444455',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Sofía',
        lastName: 'Cárdenas',
        email: 'sofia.cardenas.ex@emplifi.com',
        identityCard: '1722211100',
        department: 'Operaciones',
        position: 'Asistente de Ops',
        salary: 1000,
        phone: '0922211100',
        address: 'Quito',
        civilStatus: 'Soltera',
        contractType: 'Temporal',
        birthDate: new Date('1998-03-22'),
        hireDate: new Date('2023-06-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 3, 28), // Hace 3 meses (2 salidas)
        isActive: false,
        bankName: 'Produbanco',
        accountNumber: '4444555566',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Esteban',
        lastName: 'Ríos',
        email: 'esteban.rios.ex@emplifi.com',
        identityCard: '1711100099',
        department: 'Ventas',
        position: 'Ejecutivo de Ventas Senior',
        salary: 1800,
        phone: '0911100099',
        address: 'Quito',
        civilStatus: 'Casado',
        contractType: 'Indefinido',
        birthDate: new Date('1990-11-30'),
        hireDate: new Date('2021-08-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 2, 12), // Hace 2 meses (2 salidas)
        isActive: false,
        bankName: 'Banco Pichincha',
        accountNumber: '5555666677',
        accountType: 'Corriente',
        vacationDays: 0,
    },
    {
        firstName: 'Diana',
        lastName: 'Mejía',
        email: 'diana.mejia.ex@emplifi.com',
        identityCard: '1700099988',
        department: 'Tecnología',
        position: 'QA Tester',
        salary: 1500,
        phone: '0900099988',
        address: 'Quito',
        civilStatus: 'Soltera',
        contractType: 'Indefinido',
        birthDate: new Date('1994-08-18'),
        hireDate: new Date('2022-11-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 2, 25), // Hace 2 meses (2 salidas)
        isActive: false,
        bankName: 'Banco Internacional',
        accountNumber: '6666777788',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Gonzalo',
        lastName: 'Alvarado',
        email: 'gonzalo.alvarado.ex@emplifi.com',
        identityCard: '1799900011',
        department: 'Marketing',
        position: 'Analista SEO',
        salary: 1600,
        phone: '0999900011',
        address: 'Quito',
        civilStatus: 'Soltero',
        contractType: 'Indefinido',
        birthDate: new Date('1992-04-14'),
        hireDate: new Date('2022-01-15'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 1, 5), // Hace 1 mes (3 salidas)
        isActive: false,
        bankName: 'Banco Pichincha',
        accountNumber: '7777888899',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Elena',
        lastName: 'Salgado',
        email: 'elena.salgado.ex@emplifi.com',
        identityCard: '1788800022',
        department: 'Ventas',
        position: 'Asistente Comercial',
        salary: 1200,
        phone: '0988800022',
        address: 'Quito',
        civilStatus: 'Soltera',
        contractType: 'Temporal',
        birthDate: new Date('1996-07-28'),
        hireDate: new Date('2023-04-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 1, 18), // Hace 1 mes (3 salidas)
        isActive: false,
        bankName: 'Produbanco',
        accountNumber: '8888999900',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
    {
        firstName: 'Víctor',
        lastName: 'Paredes',
        email: 'victor.paredes.ex@emplifi.com',
        identityCard: '1777700033',
        department: 'Tecnología',
        position: 'Junior Frontend',
        salary: 1000,
        phone: '0977700033',
        address: 'Quito',
        civilStatus: 'Soltero',
        contractType: 'Temporal',
        birthDate: new Date('1999-12-05'),
        hireDate: new Date('2023-09-01'),
        exitDate: new Date(new Date().getFullYear(), new Date().getMonth() - 1, 28), // Hace 1 mes (3 salidas)
        isActive: false,
        bankName: 'Banco Guayaquil',
        accountNumber: '9999000011',
        accountType: 'Ahorros',
        vacationDays: 0,
    },
];

export async function seedUsers(prisma) {
    console.log('[USERS] Creando Admin y 10 Empleados...');
    const password = await bcrypt.hash('Emplifi2025!', 10);

    // ── Admin ──────────────────────────────────────────────────────────────────
    let admin;
    try {
        admin = await prisma.employee.upsert({
            where: { email: 'admin@emplifi.com' },
            update: { password },
            create: {
                firstName: 'Jorge',
                lastName: 'Doicela',
                email: 'admin@emplifi.com',
                role: 'admin',
                department: 'Dirección',
                position: 'Director General',
                salary: encryptSalary(5000),
                password,
                identityCard: '0101010101',
                birthDate: new Date('1980-01-01'),
                hireDate: new Date('2018-01-01'),
                isActive: true,
                address: 'Av. Patria E4-05, Quito',
                phone: '0999999999',
                civilStatus: 'Casado',
                contractType: 'Indefinido',
                bankName: encrypt('Banco Pichincha'),
                accountNumber: encrypt('0001234567'),
                accountType: 'Corriente',
                vacationDays: 15,
            }
        });
        console.log('✅ Admin: admin@emplifi.com / Emplifi2025!');
    } catch (e) {
        console.log('⚠️ Admin creation failed: ' + e.message);
        admin = await prisma.employee.findUnique({ where: { email: 'admin@emplifi.com' } });
    }

    // ── 10 Empleados ──────────────────────────────────────────────────────────
    const employees = [];
    for (const emp of EMPLOYEES) {
        try {
            const created = await prisma.employee.upsert({
                where: { email: emp.email },
                update: { password },
                create: {
                    firstName: emp.firstName,
                    lastName: emp.lastName,
                    email: emp.email,
                    password,
                    role: 'employee',
                    department: emp.department,
                    position: emp.position,
                    salary: encryptSalary(emp.salary),
                    identityCard: emp.identityCard,
                    birthDate: emp.birthDate,
                    hireDate: emp.hireDate,
                    exitDate: emp.exitDate || null,
                    isActive: emp.isActive !== undefined ? emp.isActive : true,
                    address: emp.address,
                    phone: emp.phone,
                    civilStatus: emp.civilStatus,
                    contractType: emp.contractType,
                    bankName: encrypt(emp.bankName),
                    accountNumber: encrypt(emp.accountNumber),
                    accountType: emp.accountType,
                    vacationDays: emp.vacationDays,
                }
            });
            employees.push(created);
            console.log(`✅ ${emp.firstName} ${emp.lastName}: ${emp.email} / Emplifi2025!`);
        } catch (e) {
            console.log(`⚠️ Error creando ${emp.email}: ${e.message}`);
        }
    }

    // ── Contador ─────────────────────────────────────────────────────────────
    let accountant;
    try {
        accountant = await prisma.employee.upsert({
            where: { email: 'contabilidad@emplifi.com' },
            update: { password },
            create: {
                firstName: 'Ana',
                lastName: 'Contadora',
                email: 'contabilidad@emplifi.com',
                role: 'accounting',
                department: 'Finanzas',
                position: 'Contadora Senior',
                salary: encryptSalary(2500),
                password,
                identityCard: '1799999999',
                birthDate: new Date('1985-05-20'),
                hireDate: new Date('2019-01-15'),
                isActive: true,
                address: 'Av. Gran Colombia, Quito',
                phone: '0988888888',
                civilStatus: 'Casada',
                contractType: 'Indefinido',
                bankName: encrypt('Banco Guayaquil'),
                accountNumber: encrypt('9988776655'),
                accountType: 'Corriente',
                vacationDays: 15,
            }
        });
        console.log('✅ Contabilidad: contabilidad@emplifi.com / Emplifi2025!');
    } catch (e) {
        console.log('⚠️ Accountant creation failed: ' + e.message);
    }

    // ── Emprendedor ──────────────────────────────────────────────────────────
    let entrepreneur;
    try {
        entrepreneur = await prisma.employee.upsert({
            where: { email: 'emprendedor@emplifi.com' },
            update: { password },
            create: {
                firstName: 'Carlos',
                lastName: 'Emprendedor',
                email: 'emprendedor@emplifi.com',
                role: 'entrepreneur',
                department: 'Innovación',
                position: 'Gestor de Incuadora',
                salary: encryptSalary(2800),
                password,
                identityCard: '1788888888',
                birthDate: new Date('1988-08-08'),
                hireDate: new Date('2023-01-01'),
                isActive: true,
                address: 'Cumbayá, Quito',
                phone: '0977777777',
                civilStatus: 'Soltero',
                contractType: 'Indefinido',
                bankName: encrypt('Banco del Pacífico'),
                accountNumber: encrypt('1122334455'),
                accountType: 'Ahorros',
                vacationDays: 15,
            }
        });
        console.log('✅ Emprendimiento: emprendedor@emplifi.com / Emplifi2025!');
    } catch (e) {
        console.log('⚠️ Entrepreneur creation failed: ' + e.message);
    }

    // ── System Settings ───────────────────────────────────────────────────────
    try {
        await prisma.systemSetting.upsert({
            where: { id: 'default' },
            update: {},
            create: {
                id: 'default',
                maintenanceMode: false,
                biometricEnabled: false,
                maintenanceMessage: 'El sistema estará en mantenimiento brevemente.',
            }
        });
    } catch (e) {
        console.log('⚠️ System Settings failed: ' + e.message);
    }

    // Obtener la lista real y actualizada de todos los empleados en BD
    const allUsers = await prisma.employee.findMany();
    const freshAdmin = allUsers.find(e => e.role === 'admin') || admin;
    const freshAccountant = allUsers.find(e => e.role === 'accounting') || accountant;
    const freshEntrepreneur = allUsers.find(e => e.role === 'entrepreneur') || entrepreneur;
    const freshEmployees = allUsers.filter(e => e.role === 'employee');

    return {
        admin: freshAdmin,
        employees: freshEmployees,
        accountant: freshAccountant,
        entrepreneur: freshEntrepreneur,
        allUsers
    };
}
